export const categories = [
  "Fashion & Apparel; Clothing, footwear, and accessories for all styles and occasions.",
  "Beauty & Personal Care; Skincare, haircare, makeup, and personal grooming essentials.",
  "Health & Wellness; Supplements, fitness products, and health-related services.",
  "Electronics & Gadgets; Phones, computers, home appliances, and tech accessories.",
  "Home & Living; Furniture, decor, kitchenware, and household essentials.",
  "Food & Grocery; Fresh produce, snacks, beverages, and everyday food items.",
  "Babies & Kids; Toys, clothing, gear, and essentials for children and infants.",
  "Automotive; Car accessories, parts, tools, and vehicle services.",
  "Education & Learning; Books, courses, learning materials, and academic services.",
  "Digital Products & Services; Software, e-books, templates, online tools, and digital content.",
  "Services & Freelance; Professional services including design, writing, and consulting.",
  "Sports & Outdoor; Sporting goods, activewear, and outdoor adventure gear.",
  "Books & Stationery; Novels, notebooks, school supplies, and office essentials.",
  "Pets & Animals; Pet food, accessories, and care products for all pets.",
  "Real Estate & Property; Homes, land, rentals, and property-related services.",
];

export const statesInNigeria = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT - Abuja",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
];
